import type { CurriculumSeed } from "@/features/learning/types";

/**
 * Minimal seed curriculum so the Learning Engine works without approved
 * knowledge exports. Replace / extend via KnowledgeExporter later.
 * Content mirrors early Muallim-style recognition vocabulary (Al-Fatiha).
 */
export const CURRICULUM_SEED: CurriculumSeed = {
  version: "seed-1",
  lessons: [
    {
      id: "lesson-v1-u1-l1",
      volume: 1,
      unit: 1,
      lessonNumber: 1,
      title: "پہلا سبق — تعارف اور پہچان",
      objectives: ["چند بنیادی کلمات کی پہچان", "قرآن پڑھتے ہوئے الفاظ دیکھنا"],
      pageStart: 1,
      pageEnd: 2,
    },
    {
      id: "lesson-v1-u1-l2",
      volume: 1,
      unit: 1,
      lessonNumber: 2,
      title: "دوسرا سبق — الحمد اور رب",
      objectives: ["الحمد اور رب کی پہچان مضبوط کرنا"],
      pageStart: 3,
      pageEnd: 4,
    },
  ],
  vocabulary: [
    {
      id: "vocab-bism",
      lessonId: "lesson-v1-u1-l1",
      arabic: "بِسْمِ",
      urduMeaning: "نام سے",
      root: "س م و",
      frequency: 120,
      occurrenceCount: 120,
      sourcePage: 1,
    },
    {
      id: "vocab-allah",
      lessonId: "lesson-v1-u1-l1",
      arabic: "اللّٰهِ",
      urduMeaning: "اللہ",
      root: "ا ل ه",
      frequency: 2699,
      occurrenceCount: 2699,
      sourcePage: 1,
    },
    {
      id: "vocab-rahman",
      lessonId: "lesson-v1-u1-l1",
      arabic: "الرَّحْمٰنِ",
      urduMeaning: "بڑا مہربان",
      root: "ر ح م",
      frequency: 57,
      occurrenceCount: 57,
      sourcePage: 1,
    },
    {
      id: "vocab-raheem",
      lessonId: "lesson-v1-u1-l1",
      arabic: "الرَّحِيْمِ",
      urduMeaning: "نہایت رحم والا",
      root: "ر ح م",
      frequency: 116,
      occurrenceCount: 116,
      sourcePage: 1,
    },
    {
      id: "vocab-alhamd",
      lessonId: "lesson-v1-u1-l2",
      arabic: "الْحَمْدُ",
      urduMeaning: "تعریف",
      root: "ح م د",
      frequency: 63,
      occurrenceCount: 63,
      sourcePage: 3,
    },
    {
      id: "vocab-rabb",
      lessonId: "lesson-v1-u1-l2",
      arabic: "رَبِّ",
      urduMeaning: "پروردگار",
      root: "ر ب ب",
      frequency: 970,
      occurrenceCount: 970,
      sourcePage: 3,
    },
    {
      id: "vocab-alameen",
      lessonId: "lesson-v1-u1-l2",
      arabic: "الْعٰلَمِيْنَ",
      urduMeaning: "جہانوں کے",
      root: "ع ل م",
      frequency: 73,
      occurrenceCount: 73,
      sourcePage: 3,
    },
    {
      id: "vocab-lillah",
      lessonId: "lesson-v1-u1-l2",
      arabic: "لِلّٰهِ",
      urduMeaning: "اللہ کے لیے",
      root: "ا ل ه",
      frequency: 200,
      occurrenceCount: 200,
      sourcePage: 1,
    },
    {
      id: "vocab-malik",
      lessonId: "lesson-v1-u1-l2",
      arabic: "مٰلِكِ",
      urduMeaning: "مالک",
      root: "م ل ك",
      frequency: 48,
      occurrenceCount: 48,
      sourcePage: 1,
    },
    {
      id: "vocab-yawm",
      lessonId: "lesson-v1-u1-l2",
      arabic: "يَوْمِ",
      urduMeaning: "دن",
      root: "ي و م",
      frequency: 365,
      occurrenceCount: 365,
      sourcePage: 1,
    },
    {
      id: "vocab-din",
      lessonId: "lesson-v1-u1-l2",
      arabic: "الدِّيْنِ",
      urduMeaning: "جزا / دین",
      root: "د ي ن",
      frequency: 92,
      occurrenceCount: 92,
      sourcePage: 1,
    },
    {
      id: "vocab-iyyaka",
      lessonId: "lesson-v1-u1-l2",
      arabic: "اِيَّاكَ",
      urduMeaning: "صرف تیری",
      root: null,
      frequency: 2,
      occurrenceCount: 2,
      sourcePage: 1,
    },
    {
      id: "vocab-nabudu",
      lessonId: "lesson-v1-u1-l2",
      arabic: "نَعْبُدُ",
      urduMeaning: "ہم عبادت کرتے ہیں",
      root: "ع ب د",
      frequency: 5,
      occurrenceCount: 5,
      sourcePage: 1,
    },
    {
      id: "vocab-nastaeen",
      lessonId: "lesson-v1-u1-l2",
      arabic: "نَسْتَعِيْنُ",
      urduMeaning: "ہم مدد مانگتے ہیں",
      root: "ع و ن",
      frequency: 1,
      occurrenceCount: 1,
      sourcePage: 1,
    },
    {
      id: "vocab-ihdina",
      lessonId: "lesson-v1-u1-l2",
      arabic: "اِهْدِنَا",
      urduMeaning: "ہمیں ہدایت دے",
      root: "ه د ي",
      frequency: 4,
      occurrenceCount: 4,
      sourcePage: 1,
    },
    {
      id: "vocab-sirat",
      lessonId: "lesson-v1-u1-l2",
      arabic: "الصِّرَاطَ",
      urduMeaning: "راستہ",
      root: "ص ر ط",
      frequency: 45,
      occurrenceCount: 45,
      sourcePage: 1,
    },
    {
      id: "vocab-mustaqeem",
      lessonId: "lesson-v1-u1-l2",
      arabic: "الْمُسْتَقِيْمَ",
      urduMeaning: "سیدھا",
      root: "ق و م",
      frequency: 37,
      occurrenceCount: 37,
      sourcePage: 1,
    },
  ],
  rules: [
    {
      id: "rule-v1-u1-l1-1",
      lessonId: "lesson-v1-u1-l1",
      title: "پہچان پہلے",
      explanation:
        "لفظ کا مطلب بتانے سے پہلے اسے قرآن میں پہچاننے کی کوشش کریں۔",
      examples: ["بِسْمِ اللّٰهِ", "الرَّحْمٰنِ الرَّحِيْمِ"],
      sourcePage: 1,
    },
    {
      id: "rule-v1-u1-l2-1",
      lessonId: "lesson-v1-u1-l2",
      title: "الحمد کا سیاق",
      explanation: "الحمد کو سیاقِ آیت میں پہچانیں، الگ تھلگ یاد نہ کریں۔",
      examples: ["الْحَمْدُ لِلّٰهِ رَبِّ الْعٰلَمِيْنَ"],
      sourcePage: 3,
    },
  ],
};

export function getCurriculumSeed(): CurriculumSeed {
  return CURRICULUM_SEED;
}
